CREATE TABLE saved_books(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    google_book_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    thumbnail_url VARCHAR(255),
    published_date VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE saved_books
    ADD CONSTRAINT unq_saved_books_user_id_google_book_id_name UNIQUE (user_id, google_book_id);